# Site settings
title: Diary of a Developer
email: natalie.akam@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://natstar93.github.io/" # the base hostname & protocol for your site
twitter_username: Natstar77
github_username:  natstar93

# Build settings
markdown: kramdown
jekyll serve: http://0.0.0.0:4000